FROM nikolaik/python-nodejs:python3.11-nodejs22 AS build-stage

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

RUN corepack enable

WORKDIR /workdir

COPY frontend/package.json frontend/pnpm-lock.yaml frontend/pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile --ignore-scripts

COPY . .

ENV DJANGO_ENV=production

WORKDIR /workdir/frontend
RUN pnpm exec vite build
WORKDIR /workdir
RUN python manage.py collectstatic --noinput -v2

FROM nginxinc/nginx-unprivileged:latest AS production-stage
USER root
COPY --from=build-stage --chown=nginx:root /workdir/frontend/dist /usr/share/nginx/html
COPY --from=build-stage --chown=nginx:root /workdir/static /usr/share/nginx/html/static
COPY --chown=nginx:root frontend/default.conf /etc/nginx/conf.d/default.conf
USER nginx
