FROM python:3.8

# Required by lxml Python package.
RUN apt-get update && apt-get install -y --no-install-recommends \
      libxml2-dev \
      libxslt-dev \
      gettext \
   && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

RUN groupadd -r runner && useradd --no-log-init -r -g runner runner

# Must match the directory of the settings.TOKEN_PATH default value.
RUN mkdir -p /data && chown -R runner:runner /data

WORKDIR /workdir
USER runner:runner
COPY --chown=runner:runner . .

ENV DJANGO_ENV=production
ENV WEB_CONCURRENCY=2

RUN python manage.py compilemessages

EXPOSE 8000
CMD ["gunicorn", "core.wsgi", "--bind", "0.0.0.0:8000", "--worker-tmp-dir", "/dev/shm", "--threads", "2", "--name", "pelican-frontend"]
