# Generated by Django 5.2.17 on 2026-08-23 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "language",
                    models.CharField(blank=True, help_text="The user's preferred language", max_length=255),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="The publisher's name", max_length=255)),
                (
                    "spider",
                    models.CharField(
                        help_text="The spider's name in Kingfisher Collect, like chile_compra_bulk",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("users", models.ManyToManyField(blank=True, related_name="publishers", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
