# Generated by Django 5.2.17 on 2026-08-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="language",
            field=models.TextField(blank=True, help_text="The user's preferred language"),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="name",
            field=models.TextField(help_text="The publisher's name"),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="spider",
            field=models.TextField(help_text="The spider's name in Kingfisher Collect", unique=True),
        ),
    ]
