/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/data_items/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Return OCDS data that passed or failed a check. */
    get: operations["data_items_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/dataset-distinct-values/{dataset_id}/{field}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Return the field's 200 most common values, with their counts, in descending order. */
    get: operations["dataset_distinct_values"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/dataset-distinct-values/{dataset_id}/{field}/{query}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Return the field's 200 most common values containing the query, with their counts, in descending order. */
    get: operations["dataset_distinct_values_search"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/dataset-filter-items/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * @description Return the number of data items that the filter matches, as an object.
     *
     *     ``{"items": 123}`` for example.
     */
    post: operations["dataset_filter_items_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/datasets/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Return all datasets with their status and filter metadata. */
    get: operations["datasets_list"];
    put?: never;
    /** @description Publish a message to RabbitMQ to create a dataset. */
    post: operations["datasets_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/datasets/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Return the dataset with its status and filter metadata. */
    get: operations["datasets_retrieve"];
    put?: never;
    post?: never;
    /** @description Publish a message to RabbitMQ to wipe the dataset. */
    delete: operations["datasets_destroy"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/datasets/{id}/compiled_release_level/{name}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Return a report and examples of one compiled release-level check. */
    get: operations["datasets_compiled_release_level_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/datasets/{id}/compiled_release_level/{name}/failures/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Return, one OCID per line, the compiled releases failing the compiled release-level check. */
    get: operations["datasets_compiled_release_level_failures_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/datasets/{id}/compiled_release_level_report/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Return a report of the dataset's compiled release-level checks, by check name. */
    get: operations["datasets_compiled_release_level_report_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/datasets/{id}/dataset_level_report/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Return a report of the dataset's dataset-level checks, by check name. */
    get: operations["datasets_dataset_level_report_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/datasets/{id}/field_level/{name}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Return a report and examples of one field-level check. */
    get: operations["datasets_field_level_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/datasets/{id}/field_level/{name}/failures/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Return, one OCID per line, the compiled releases failing the field-level check. */
    get: operations["datasets_field_level_failures_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/datasets/{id}/field_level_report/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Return a report of the dataset's field-level checks, by field path. */
    get: operations["datasets_field_level_report_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/datasets/{id}/filter/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Publish a message to RabbitMQ to create a filtered dataset. */
    post: operations["datasets_filter_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/datasets/{id}/time_based_report/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Return a report of the dataset's time-based checks, by check name. */
    get: operations["datasets_time_based_report_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/exports/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Publish a message to RabbitMQ to create a report in Google Docs, and return the export to poll. */
    post: operations["exports_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/exports/{id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description Return the export, whose ``status`` is ``waiting`` until the report is created.
     *
     *     If the report is created, the export has a ``document_id``, and might have ``failed_checks``.
     *     Otherwise, its ``status`` is ``error``, with a ``reason``, or ``template_error``, with ``errors``.
     */
    get: operations["exports_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/schema/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
     *
     *     - YAML: application/vnd.oai.openapi
     *     - JSON: application/vnd.oai.openapi+json
     */
    get: operations["schema_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/settings/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Return the reader's own settings, and the settings that the frontend needs in order to generate a report. */
    get: operations["settings_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** @description Update the reader's own settings, which follow them between browsers. */
    patch: operations["settings_partial_update"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CollectionMetadata: {
      /** @description The publisher's name */
      publisher: string | null;
      /** @description The OCID prefix */
      ocid_prefix: string | null;
      /** @description The earliest release date */
      published_from: string | null;
      /** @description The latest release date */
      published_to: string | null;
      /** @description The URL of the data license */
      data_license: string | null;
      /** @description The URL of the publication policy */
      publication_policy: string | null;
      /** @description The declared extensions */
      extensions: unknown[];
    };
    CompiledReleases: {
      /** @description The number of distinct OCIDs */
      total_unique_ocids: number;
    };
    CountDatasetFilterItems: {
      /** @description The ID of the dataset to filter */
      dataset_id_original: number;
      /** @description The filter to apply */
      filter_message: components["schemas"]["FilterDataset"];
    };
    CreateDataset: {
      /** @description The name to assign to the dataset, using {spider}_{YYYY-MM-DD} to share it with the publisher */
      name: string;
      /** @description The compiled collection ID in Kingfisher Process */
      collection_id: number;
      /** @description The ID of the previous report in Pelican, for time-based checks */
      ancestor_id?: number;
      /** @description The number of compiled releases to import from Kingfisher Process */
      max_items?: number;
    };
    CreateExport: {
      /**
       * Format: int64
       * @description The dataset's ID
       */
      dataset_id: number;
      /** @description The ID of the Google Docs template */
      template_id: string;
      /** @description The ID of the Google Drive folder in which to create the report */
      folder_id: string;
      /** @description The report's language, defaulting to English */
      language?: string;
      /** @description The report's filename, defaulting to a generated name */
      name?: string;
    };
    DataItem: {
      readonly id: number;
      data: unknown;
    };
    Dataset: {
      readonly id: number;
      name: string;
      meta: components["schemas"]["DatasetMeta"];
      /** Format: int64 */
      ancestor_id?: number | null;
      /** Format: date-time */
      created?: string | null;
      /** Format: date-time */
      modified?: string | null;
      phase: string;
      state: string;
      /** @description The ID of the dataset that was filtered */
      parent_id: number | null;
      /** @description The name of the dataset that was filtered */
      parent_name: string | null;
      /** @description The filter that created the dataset */
      filter_message: components["schemas"]["FilterDataset"] | null;
    };
    DatasetLevelCheck: {
      /** @description Whether the check passed, or null if not applicable */
      result: boolean | null;
      value: number | null;
      /** @description Any additional data to help interpret the result. Its properties vary by check. */
      meta: unknown;
    };
    DatasetLevelReport: {
      [key: string]: components["schemas"]["DatasetLevelCheck"];
    };
    DatasetMeta: {
      collection_metadata: components["schemas"]["CollectionMetadata"];
      kingfisher_metadata: components["schemas"]["KingfisherMetadata"];
      data_quality_tool_metadata?: components["schemas"]["PelicanMetadata"];
      compiled_releases: components["schemas"]["CompiledReleases"];
      /** @description The number of objects in each stage */
      tender_lifecycle: components["schemas"]["TenderLifecycle"];
    };
    DistinctValue: {
      /** @description The field's value */
      value: string;
      /** @description The number of data items with this value */
      count: number;
    };
    ExampleMeta: {
      /** @description The compiled release's OCID */
      ocid: string;
      /** @description The data item's ID */
      item_id: number;
    };
    Export: {
      readonly id: number;
      /**
       * @description Whether the report is waiting to be created, was created, or failed
       *
       *     * `waiting` - Waiting
       *     * `ok` - Ok
       *     * `error` - Error
       *     * `template_error` - Template Error
       */
      readonly status: components["schemas"]["StatusEnum"];
      /** @description The ID of the exported document in Google Docs */
      readonly document_id: string;
      /** @description The reason the report couldn't be created */
      readonly reason: string;
      readonly errors: components["schemas"]["ExportError"][];
      /** @description The checks that couldn't be computed */
      readonly failed_checks: string[];
    };
    ExportError: {
      /** @description The reason the template couldn't be rendered */
      readonly reason: string;
      /** @description The tag as extracted from the template */
      readonly tag: string;
      /** @description The ID of the Google Docs template */
      readonly template_id: string;
    };
    FieldLevelCheck: {
      coverage: components["schemas"]["FieldLevelGroup"];
      quality: components["schemas"]["FieldLevelGroup"];
      /** @description Whether the examples are filled in */
      examples_filled: boolean;
      /** @description The order in which to display the field */
      processing_order: number;
    };
    FieldLevelCheckDetail: {
      coverage: components["schemas"]["FieldLevelGroupDetail"];
      quality: components["schemas"]["FieldLevelGroupDetail"];
      /** @description Whether the examples are filled in */
      examples_filled: boolean;
      /** @description The order in which to display the field */
      processing_order: number;
      /**
       * Format: double
       * @description The duration of the request, in seconds
       */
      time: number;
    };
    FieldLevelCounts: {
      /** @description The number of times the check was applied */
      total_count: number;
      /** @description The number of times the check passed */
      passed_count: number;
      /** @description The number of times the check failed */
      failed_count: number;
      passed_examples?: components["schemas"]["FieldLevelExample"][];
      failed_examples?: components["schemas"]["FieldLevelExample"][];
    };
    FieldLevelCountsDetail: {
      /** @description The number of times the check was applied */
      total_count: number;
      /** @description The number of times the check passed */
      passed_count: number;
      /** @description The number of times the check failed */
      failed_count: number;
      passed_examples: components["schemas"]["FieldLevelExample"][];
      failed_examples: components["schemas"]["FieldLevelExample"][];
    };
    FieldLevelExample: {
      meta: components["schemas"]["ExampleMeta"];
      /** @description The field's path */
      path: string;
      result: components["schemas"]["FieldLevelExampleResult"];
    };
    FieldLevelExampleResult: {
      /** @description The check's name */
      name: string;
      /** @description Whether the check passed */
      result: boolean;
      /** @description The reason the check failed */
      reason: string | null;
      /** @description The field's value, if the check failed */
      value: unknown;
      /**
       * Format: double
       * @description The check's version
       */
      version: number;
    };
    FieldLevelGroup: {
      /** @description The number of times the check was applied */
      total_count: number;
      /** @description The number of times the check passed */
      passed_count: number;
      /** @description The number of times the check failed */
      failed_count: number;
      passed_examples?: components["schemas"]["FieldLevelExample"][];
      failed_examples?: components["schemas"]["FieldLevelExample"][];
      /** @description The checks, by name */
      checks: {
        [key: string]: components["schemas"]["FieldLevelCounts"];
      };
    };
    FieldLevelGroupDetail: {
      /** @description The number of times the check was applied */
      total_count: number;
      /** @description The number of times the check passed */
      passed_count: number;
      /** @description The number of times the check failed */
      failed_count: number;
      passed_examples: components["schemas"]["FieldLevelExample"][];
      failed_examples: components["schemas"]["FieldLevelExample"][];
      /** @description The checks, by name */
      checks: {
        [key: string]: components["schemas"]["FieldLevelCountsDetail"];
      };
    };
    FieldLevelReport: {
      [key: string]: components["schemas"]["FieldLevelCheck"];
    };
    FilterDataset: {
      /** @description The minimum release date (YYYY-MM-DD) */
      release_date_from?: string;
      /** @description The maximum release date (YYYY-MM-DD) */
      release_date_to?: string;
      /** @description Names of buyers */
      buyer?: string[];
      /** @description A SQL ILIKE pattern for the buyer's name */
      buyer_regex?: string;
      /** @description Names of procuring entities */
      procuring_entity?: string[];
      /** @description A SQL ILIKE pattern for the procuring entity's name */
      procuring_entity_regex?: string;
    };
    KingfisherMetadata: {
      /** @description The compiled collection ID in Kingfisher Process */
      collection_id?: number;
      /** @description When Kingfisher Process started storing the original collection */
      processing_start?: string;
      /** @description When Kingfisher Process finished storing the compiled collection */
      processing_end?: string;
    };
    /**
     * @description * `en` - en
     *     * `es` - es
     * @enum {string}
     */
    LanguageEnum: "en" | "es";
    PatchedUserSettings: {
      /**
       * @description The user's preferred language
       *
       *     * `en` - en
       *     * `es` - es
       */
      language?: components["schemas"]["LanguageEnum"];
    };
    PelicanMetadata: {
      /** @description When Pelican started processing the dataset */
      processing_start: string;
      /** @description When Pelican finished processing the dataset */
      processing_end: string;
    };
    ResourceLevelCheck: {
      /** @description The check's name */
      name: string;
      /** @description The number of compiled releases to which the check was applied */
      total_count: number;
      /** @description The number of compiled releases that passed */
      passed_count: number;
      /** @description The number of compiled releases that failed */
      failed_count: number;
      /** @description The number of compiled releases for which the check was inapplicable */
      undefined_count: number;
      /** @description The number of times the check was applied */
      individual_application_count: number;
      /** @description The number of times the check passed */
      individual_passed_count: number;
      /** @description The number of times the check failed */
      individual_failed_count: number;
      /** @description Whether the examples are filled in */
      examples_filled: boolean;
      passed_examples: components["schemas"]["ResourceLevelExample"][];
      failed_examples: components["schemas"]["ResourceLevelExample"][];
      undefined_examples: components["schemas"]["ResourceLevelExample"][];
    };
    ResourceLevelCheckDetail: {
      /** @description The check's name */
      name: string;
      /** @description The number of compiled releases to which the check was applied */
      total_count: number;
      /** @description The number of compiled releases that passed */
      passed_count: number;
      /** @description The number of compiled releases that failed */
      failed_count: number;
      /** @description The number of compiled releases for which the check was inapplicable */
      undefined_count: number;
      /** @description The number of times the check was applied */
      individual_application_count: number;
      /** @description The number of times the check passed */
      individual_passed_count: number;
      /** @description The number of times the check failed */
      individual_failed_count: number;
      /** @description Whether the examples are filled in */
      examples_filled: boolean;
      passed_examples: components["schemas"]["ResourceLevelExample"][];
      failed_examples: components["schemas"]["ResourceLevelExample"][];
      undefined_examples: components["schemas"]["ResourceLevelExample"][];
      /**
       * Format: double
       * @description The duration of the request, in seconds
       */
      time: number;
    };
    ResourceLevelExample: {
      meta: components["schemas"]["ExampleMeta"];
      result: components["schemas"]["ResourceLevelExampleResult"];
    };
    ResourceLevelExampleResult: {
      /** @description Whether the check passed */
      result: boolean | null;
      /** @description Any additional data to help interpret the result. Its properties vary by check. */
      meta: unknown;
      /** @description The number of times the check passed */
      pass_count: number | null;
      /** @description The number of times the check was applied */
      application_count: number | null;
      /**
       * Format: double
       * @description The check's version
       */
      version: number;
    };
    ResourceLevelReport: {
      [key: string]: components["schemas"]["ResourceLevelCheck"];
    };
    Settings: {
      /** @description The user's preferred language */
      language: string;
      /** @description The user's name */
      username: string;
      /** @description The service account that the template and folder must be shared with */
      user: string;
      /** @description The ID of the default Google Docs template, by language */
      template: {
        [key: string]: string;
      };
      /** @description The ID of the default Google Drive folder in which to create reports, or blank for non-staff */
      folder: string;
    };
    /**
     * @description * `waiting` - Waiting
     *     * `ok` - Ok
     *     * `error` - Error
     *     * `template_error` - Template Error
     * @enum {string}
     */
    StatusEnum: "waiting" | "ok" | "error" | "template_error";
    TenderLifecycle: {
      planning: number;
      tender: number;
      award: number;
      contract: number;
      implementation: number;
    };
    TimeVarianceExample: {
      /** @description The pair's OCID */
      ocid: string;
      /** @description The data item's ID in the ancestor dataset */
      item_id: number;
      /** @description The same value as ocid, since a pair is matched on it */
      new_item_ocid: string;
      /** @description The data item's ID in this dataset */
      new_item_id: number;
    };
    /** @description A pair is a compiled release in the ancestor dataset and the one with the same OCID in this dataset. */
    TimeVarianceLevelCheck: {
      /** @description The percentage of the ancestor dataset's applicable compiled releases that are paired, or null if the check applied to none */
      coverage_value: number | null;
      /** @description Whether coverage_value exceeds 95 */
      coverage_result: boolean | null;
      /** @description The percentage of pairs that passed, or null if none were found */
      check_value: number | null;
      /** @description Whether check_value exceeds 95 */
      check_result: boolean | null;
      meta: components["schemas"]["TimeVarianceMeta"];
    };
    TimeVarianceLevelReport: {
      [key: string]: components["schemas"]["TimeVarianceLevelCheck"];
    };
    TimeVarianceMeta: {
      /** @description The number of the ancestor dataset's compiled releases to which the check applies */
      total_count: number;
      /** @description The number of the ancestor dataset's applicable compiled releases that are paired */
      coverage_count: number;
      /** @description The number of pairs that passed */
      ok_count: number;
      /** @description The number of pairs that failed */
      failed_count: number;
      /** @description A sample of up to 50 pairs that failed */
      examples: components["schemas"]["TimeVarianceExample"][];
      /**
       * Format: double
       * @description The check's version
       */
      version: number;
    };
    UserSettings: {
      /**
       * @description The user's preferred language
       *
       *     * `en` - en
       *     * `es` - es
       */
      language: components["schemas"]["LanguageEnum"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  data_items_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DataItem"];
        };
      };
    };
  };
  dataset_distinct_values: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        dataset_id: number;
        field: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DistinctValue"][];
        };
      };
    };
  };
  dataset_distinct_values_search: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        dataset_id: number;
        field: string;
        query: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DistinctValue"][];
        };
      };
    };
  };
  dataset_filter_items_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CountDatasetFilterItems"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            items?: number;
          };
        };
      };
    };
  };
  datasets_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Dataset"][];
        };
      };
    };
  };
  datasets_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateDataset"];
      };
    };
    responses: {
      /** @description No response body */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
    };
  };
  datasets_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Dataset"];
        };
      };
    };
  };
  datasets_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  datasets_compiled_release_level_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResourceLevelCheckDetail"];
        };
      };
    };
  };
  datasets_compiled_release_level_failures_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
    };
  };
  datasets_compiled_release_level_report_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResourceLevelReport"];
        };
      };
    };
  };
  datasets_dataset_level_report_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DatasetLevelReport"];
        };
      };
    };
  };
  datasets_field_level_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FieldLevelCheckDetail"];
        };
      };
    };
  };
  datasets_field_level_failures_retrieve: {
    parameters: {
      query?: {
        /** @description The type of check */
        type?: "coverage" | "quality";
      };
      header?: never;
      path: {
        id: number;
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
    };
  };
  datasets_field_level_report_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FieldLevelReport"];
        };
      };
    };
  };
  datasets_filter_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["FilterDataset"];
      };
    };
    responses: {
      /** @description No response body */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  datasets_time_based_report_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TimeVarianceLevelReport"];
        };
      };
    };
  };
  exports_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateExport"];
      };
    };
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Export"];
        };
      };
    };
  };
  exports_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Export"];
        };
      };
    };
  };
  schema_retrieve: {
    parameters: {
      query?: {
        format?: "json" | "yaml";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/vnd.oai.openapi": {
            [key: string]: unknown;
          };
          "application/yaml": {
            [key: string]: unknown;
          };
          "application/vnd.oai.openapi+json": {
            [key: string]: unknown;
          };
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  settings_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Settings"];
        };
      };
    };
  };
  settings_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedUserSettings"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserSettings"];
        };
      };
    };
  };
}
