# Generated by Django 5.2.17 on 2026-08-24 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Export",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dataset_id", models.BigIntegerField(help_text="The dataset's ID")),
                ("document_id", models.CharField(help_text="The ID of the Google Docs template", max_length=255)),
                (
                    "folder_id",
                    models.CharField(
                        help_text="The ID of the Google Drive folder in which to create the report", max_length=255
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, help_text="The report's language, defaulting to English", max_length=255
                    ),
                ),
                (
                    "report_name",
                    models.CharField(
                        blank=True, help_text="The report's filename, defaulting to a generated name", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("ok", "Ok"),
                            ("report_error", "Report Error"),
                            ("template_error", "Template Error"),
                        ],
                        default="waiting",
                        help_text="Whether the report is waiting to be created, was created, or failed",
                        max_length=255,
                    ),
                ),
                (
                    "file_id",
                    models.CharField(blank=True, help_text="The ID of the Google Docs report", max_length=255),
                ),
                ("reason", models.TextField(blank=True, help_text="The reason the report could not be created")),
                (
                    "tag_errors",
                    models.JSONField(
                        blank=True, default=list, help_text="The errors that stopped the template from rendering"
                    ),
                ),
                (
                    "failed_tags",
                    models.JSONField(blank=True, default=list, help_text="The tags that could not be rendered"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
