# Generated by Django 5.2.17 on 2026-08-25 18:57

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Export",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dataset_id", models.BigIntegerField(help_text="The dataset's ID")),
                ("template_id", models.TextField(help_text="The ID of the Google Docs template")),
                (
                    "folder_id",
                    models.TextField(help_text="The ID of the Google Drive folder in which to create the report"),
                ),
                ("language", models.TextField(blank=True, help_text="The report's language, defaulting to English")),
                (
                    "name",
                    models.TextField(blank=True, help_text="The report's filename, defaulting to a generated name"),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("ok", "Ok"),
                            ("error", "Error"),
                            ("template_error", "Template Error"),
                        ],
                        default="waiting",
                        help_text="Whether the report is waiting to be created, was created, or failed",
                    ),
                ),
                (
                    "document_id",
                    models.TextField(blank=True, help_text="The ID of the exported document in Google Docs"),
                ),
                ("reason", models.TextField(blank=True, help_text="The reason the report couldn't be created")),
                (
                    "failed_checks",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        help_text="The checks that couldn't be computed",
                        size=None,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExportError",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.TextField(help_text="The reason the template couldn't be rendered")),
                ("tag", models.TextField(blank=True, help_text="The tag as extracted from the template")),
                ("template_id", models.TextField(blank=True, help_text="The ID of the Google Docs template")),
                (
                    "export",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="errors", to="exporter.export"
                    ),
                ),
            ],
        ),
    ]
