name: Translations
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', 'setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install translate-toolkit
        run: |
          sudo apt update
          sudo apt install gettext translate-toolkit
      # Don't install editable projects in the current working directory.
      # https://pip.pypa.io/en/latest/reference/pip_install/#install-src
      - run: pip install --src $GITHUB_WORKSPACE/../src -r requirements.txt
      - run: python manage.py makemessages -a
      - name: Count incomplete translations
        run: |
          output=$(find . -name LC_MESSAGES -not -path "*/en_US/*" -exec pocount --incomplete --short "{}" +)
          echo $output
          [ "$output" = "" ]
