name: Lint
on: [push, pull_request]
jobs:
  lint:
    uses: open-contracting/.github/.github/workflows/lint.yml@main
    permissions:
      contents: write
    with:
      ocds-schema-exceptions: release-schema.json
      standard-maintenance-scripts-files: requirements_base.in
    secrets:
      personal-access-token: ${{ secrets.PAT }}
